services:
  backend:
    build:
      context: ./backend
    container_name: face-detection-backend
    env_file:
      - ./backend/.env
    environment:
      PORT: 5000
    restart: unless-stopped
    networks:
      - opencv-net

  frontend:
    build:
      context: ./frontend
    container_name: face-detection-frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - opencv-net

networks:
  opencv-net:
    driver: bridge
